services:   
  api: 
    build:
      context: ./Backend/PixelDread
      dockerfile: Dockerfile
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/pixeldread.db
    volumes:
      - db-data:/app/data
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge

volumes:
   db-data: 